version: "3.8"

services:
  mysqldb:
    image: mysql:8.3.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DB_DOCKER_PORT
  app:
    depends_on:
      - mysqldb
    image: wine_library
    restart: unless-stopped
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mariadb://mysqldb:$MYSQL_DB_DOCKER_PORT/$MYSQLDB_DATABASE?serverTimezone=UTC&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "validate",
        "stripe.secret.key" : "$STRIPE_SECRET_KEY",
        "stripe.success.url" : "http://localhost:$SPRING_LOCAL_PORT/payments/success?orderId=",
        "stripe.cancel.url" : "http://localhost:$SPRING_LOCAL_PORT/payments/cancel?orderId=",
        "deepseek.url" : "$DEEPSEEK_URL",
        "deepseek.key" : "$DEEPSEEK_KEY",
        "spring.security.oauth2.client.registration.google.client-id" : "$OAUTH_GOOGLE_CLIENT_ID",
        "spring.security.oauth2.client.registration.google.client-secret" : "$OAUTH_GOOGLE_CLIENT_SECRET",
        "spring.security.oauth2.client.registration.google.redirect-uri" : "http://localhost:$SPRING_LOCAL_PORT/login/oauth2/code/google"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
